import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, phone, service, projectType, message, company } = body;

    const selectedService = service || projectType || "General Inquiry";
    const contactPhone = phone || "Not Provided";

    // Validate required inputs
    if (!name || !email || !message) {
      return NextResponse.json(
        { error: "Name, email, and message are required fields." },
        { status: 400 }
      );
    }

    // Configure Nodemailer transporter
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "smtp.example.com",
      port: parseInt(process.env.SMTP_PORT || "587"),
      secure: process.env.SMTP_PORT === "465", // true for 465 SSL, false for other ports (TLS/STARTTLS)
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASSWORD,
      },
    });

    const recipient = process.env.CONTACT_EMAIL || "info@tapclone.com";

    // Compose HTML content for the email
    const emailHtml = `
      <div style="font-family: sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #e5e7eb; border-radius: 12px; background-color: #ffffff;">
        <h2 style="color: #4ab012; margin-top: 0; font-size: 22px; font-weight: bold; border-bottom: 2px solid #6EE31A; padding-bottom: 8px;">New Lead Received - TapClone</h2>
        <p style="font-size: 14px; color: #666;">You have received a new lead inquiry from the TapClone landing page form.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <tr>
            <td style="padding: 10px 8px; font-weight: bold; width: 140px; border-bottom: 1px solid #f3f4f6; font-size: 14px; color: #555;">Name:</td>
            <td style="padding: 10px 8px; border-bottom: 1px solid #f3f4f6; font-size: 14px; font-weight: bold; color: #111;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 10px 8px; font-weight: bold; border-bottom: 1px solid #f3f4f6; font-size: 14px; color: #555;">Email:</td>
            <td style="padding: 10px 8px; border-bottom: 1px solid #f3f4f6; font-size: 14px;"><a href="mailto:${email}" style="color: #4ab012; text-decoration: none; font-weight: 500;">${email}</a></td>
          </tr>
          <tr>
            <td style="padding: 10px 8px; font-weight: bold; border-bottom: 1px solid #f3f4f6; font-size: 14px; color: #555;">Phone:</td>
            <td style="padding: 10px 8px; border-bottom: 1px solid #f3f4f6; font-size: 14px; color: #111;">${contactPhone}</td>
          </tr>
          ${company ? `
          <tr>
            <td style="padding: 10px 8px; font-weight: bold; border-bottom: 1px solid #f3f4f6; font-size: 14px; color: #555;">Company:</td>
            <td style="padding: 10px 8px; border-bottom: 1px solid #f3f4f6; font-size: 14px; color: #111;">${company}</td>
          </tr>
          ` : ""}
          <tr>
            <td style="padding: 10px 8px; font-weight: bold; border-bottom: 1px solid #f3f4f6; font-size: 14px; color: #555;">Service Requested:</td>
            <td style="padding: 10px 8px; border-bottom: 1px solid #f3f4f6; font-size: 14px; color: #4ab012; font-weight: bold;">${selectedService}</td>
          </tr>
        </table>
        
        <div style="margin-top: 20px;">
          <p style="font-weight: bold; margin-bottom: 6px; font-size: 14px; color: #555;">Message:</p>
          <div style="background-color: #f9fafb; padding: 15px; border-radius: 8px; border: 1px solid #e5e7eb; font-size: 14px; color: #333; line-height: 1.5; font-style: italic; white-space: pre-wrap;">
            "${message}"
          </div>
        </div>
        
        <div style="margin-top: 25px; font-size: 11px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 12px;">
          This email was auto-generated by the TapClone Landing Page submission portal.
        </div>
      </div>
    `;

    // Send the email message
    await transporter.sendMail({
      from: `"TapClone Web Lead" <${process.env.SMTP_USER}>`,
      to: recipient,
      subject: `New Lead: ${selectedService} - ${name}`,
      text: `New lead from ${name} (${email}, ${contactPhone}${company ? `, Company: ${company}` : ""}) for ${selectedService}: ${message}`,
      html: emailHtml,
    });

    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error("Error sending email:", error);
    return NextResponse.json(
      { error: "Internal server error. Failed to process submission." },
      { status: 500 }
    );
  }
}
